SOMOSDASWEBAPP/Controllers/CursosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SOMOSDASWEBAPP.Context;
using SOMOSDASWEBAPP.Models;

namespace SOMOSDASWEBAPP.Controllers
{
    public class CursosController : Controller
    {
        private readonly MyContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public CursosController(MyContext context , IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;

        }

        // GET: Cursos
        public async Task<IActionResult> Index(string search)
        {
            ICollection<Curso> Cursos;

            if (string.IsNullOrEmpty(search))
            {
                Cursos = await _context.Curso
                    .OrderBy(x => x.CodCurso)
                    .ToListAsync();
            }
            else
            {
                Cursos = await _context.Curso
                    .Where(x => x.CodCurso.ToString().Contains(search))
                    .OrderBy(x => x.CodCurso)
                    .ToListAsync();
            }
            return _context.Curso != null ? 
                          View(Cursos) :
                          Problem("Entity set 'MyContext.Curso'  is null.");
        }

        // GET: Cursos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Curso == null)
            {
                return NotFound();
            }

            var curso = await _context.Curso
                .FirstOrDefaultAsync(m => m.CodCurso == id);
            if (curso == null)
            {
                return NotFound();
            }

            return View(curso);
        }

        // GET: Cursos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Cursos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CodCurso,Duracion,Tema,Docente,CuposCurso,Tipo")] Curso curso)
        {
            if (ModelState.IsValid)
            {
                _context.Add(curso);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(curso);
        }

        // GET: Cursos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Curso == null)
            {
                return NotFound();
            }

            var curso = await _context.Curso.FindAsync(id);
            if (curso == null)
            {
                return NotFound();
            }
            return View(curso);
        }

        // POST: Cursos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CodCurso,Duracion,Tema,Docente,CuposCurso,Tipo,")] Curso curso)
        {
            if (id != curso.CodCurso)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    //cargar la foto
                    if (curso.FotoFile != null)
                    {
                        await SubirFoto(curso);
                    }

                    _context.Update(curso);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CursoExists(curso.CodCurso))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(curso);
        }

        private async Task SubirFoto(Curso curso)
        {
            //formar el nombre del archivo foto
            string wwRootPath = _webHostEnvironment.WebRootPath;
            string extension = Path.GetExtension(curso.FotoFile!.FileName);
            string nombreFoto = $"{curso.CodCurso}{extension}";

          //  curso.Foto = nombreFoto;

            //copiar la foto en el proyecto del servidor
            string path = Path.Combine($"{wwRootPath}/pictures/cursos", nombreFoto);
            var fileStream = new FileStream(path, FileMode.Create);
            await curso.FotoFile.CopyToAsync(fileStream);
        }

        // GET: Cursos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Curso == null)
            {
                return NotFound();
            }

            var curso = await _context.Curso
                .FirstOrDefaultAsync(m => m.CodCurso == id);
            if (curso == null)
            {
                return NotFound();
            }

            return View(curso);
        }

        // POST: Cursos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Curso == null)
            {
                return Problem("Entity set 'MyContext.Curso'  is null.");
            }
            var curso = await _context.Curso.FindAsync(id);
            if (curso != null)
            {
                _context.Curso.Remove(curso);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CursoExists(int id)
        {
          return (_context.Curso?.Any(e => e.CodCurso == id)).GetValueOrDefault();
        }
    }
}

SOMOSDASWEBAPP/Controllers/ReporteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SOMOSDASWEBAPP.Context;
using SOMOSDASWEBAPP.Models;

namespace SOMOSDASWEBAPP.Controllers
{
    
    public class ReporteController : Controller
    {
        private readonly MyContext _myContext;
        public  ReporteController(MyContext myContext) {
            _myContext = myContext;
        }  
           public IActionResult Index()
        {
            int idUsuario = int.Parse(User.Claims.ToList()[2].Value);
            var usuario = _myContext.Usuario
            .Where(x => x.Id == idUsuario)
            .Include(x => x.Inscripciones)
            .FirstOrDefault();
            return View(usuario);
        }
    }
}

SOMOSDASWEBAPP/Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SOMOSDASWEBAPP.Context;
using SOMOSDASWEBAPP.Models;

namespace SOMOSDASWEBAPP.Controllers
{
    [Authorize(Roles = "Director")]
    public class UsuariosController : Controller
    {
        private readonly MyContext _context;

        public UsuariosController(MyContext context)
        {
            _context = context;
        }

        // GET: Usuarios
        public async Task<IActionResult> Index(string search)
        {
            ICollection<Usuario> Usuario;

            if (string.IsNullOrEmpty(search))
            {
                Usuario = await _context.Usuario
                    .OrderBy(x => x.NombreCompleto)
                    .ToListAsync();
            }
            else
            {
                Usuario = await _context.Usuario
                    .Where(x =>  x.NombreCompleto!.Contains(search))
                    .OrderBy(x => x.NombreCompleto)
                    .ToListAsync();
            }

            return _context.Usuario != null ?
                        View(Usuario) :
                        Problem("Entity set 'MiContext.Usuario'  is null.");
        }
        // GET: Usuarios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Usuario == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuario
                .FirstOrDefaultAsync(m => m.Id == id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        // GET: Usuarios/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Usuarios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Email,Password,NombreCompleto,Rol")] Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                _context.Add(usuario);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(usuario);
        }

        // GET: Usuarios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Usuario == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuario.FindAsync(id);
            if (usuario == null)
            {
                return NotFound();
            }
            return View(usuario);
        }

        // POST: Usuarios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Email,Password,NombreCompleto,Rol")] Usuario usuario)
        {
            if (id != usuario.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(usuario);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UsuarioExists(usuario.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(usuario);
        }

        // GET: Usuarios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Usuario == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuario
                .FirstOrDefaultAsync(m => m.Id == id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        // POST: Usuarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Usuario == null)
            {
                return Problem("Entity set 'MyContext.Usuario'  is null.");
            }
            var usuario = await _context.Usuario.FindAsync(id);
            if (usuario != null)
            {
                _context.Usuario.Remove(usuario);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UsuarioExists(int id)
        {
          return (_context.Usuario?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

SOMOSDASWEBAPP/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@using System.Security.Claims;

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SOMOSDASWEBAPP</title>

    <!--  <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
     <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
       <link rel="stylesheet" href="~/SOMOSDASWEBAPP.styles.css" asp-append-version="true" />-->
    <link rel="stylesheet" href="~/css/inicio.css">
    <link rel="stylesheet" href="~/css/style_login.css">
    <script src="https://kit.fontawesome.com/fb4f4ab695.js" crossorigin="anonymous"></script>

</head>
<body>
    <header class="portada">
        <h1>SomosDas</h1>
        <!-- <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SOMOSDASWEBAPP</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav> -->
    </header>
    <div class="cajaM">
        <div class="menu">
            @if (User.IsInRole("Director") || User.IsInRole("Secretaria"))
            {
                <div>
                    <a asp-area="" asp-controller="Home" asp-action="Index"><i class="fas fa-home"></i>  Inicio</a>
                </div>
                <div>
                    <a asp-area="" asp-controller="Estudiantes" asp-action="Index"><i class="fas fa-user-plus"></i>  Gestor de Alumnos</a>
                </div>
                <div>
                    <a asp-area="" asp-controller="Cursos" asp-action="Index"><i class="fas fa-book-open"></i>  Gestor de Cursos</a>
                </div>
                <div>
                    <a asp-area="" asp-controller="Reporte" asp-action="Index"><i class="fas fa-table"></i>  Reporte de Caja</a>
                </div>
                @if (User.IsInRole("Director"))
                {
                    <div>
                        <a asp-area="" asp-controller="Usuarios" asp-action="Index"><i class="fas fa-user-tie"></i>  Gestor de Usuarios</a>
                    </div>
                }
                <div>
                    <a asp-area="" asp-controller="Inscripcions" asp-action="Index"><i class="fas fa-book-open"></i>  Inscripcion</a>
                </div>
            }
            else
            {
                
                <div>
                    <a asp-area="" asp-controller="Home" asp-action="Index"><i class="fas fa-home"></i>  Inicio</a>
                </div>
            }

            <div class="d-flex">
                <span class="navbar-text">
                    @User.Identity?.Name | @User.FindFirstValue(ClaimTypes.Role)
                </span>

                <a class="nav-link" asp-controller="Login" asp-action="Logout">Salir</a>
            </div>



        </div>

        <div class="content">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    </div>

    <!--   <footer class="border-top footer text-muted">
          <div class="container">
              &copy; 2023 - SOMOSDASWEBAPP - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
          </div>
      </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
      <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
      

      -->
    @RenderSection("Scripts", required: false)
</body>
</html>